### ISSUE TITLE
adding features from "Not Implemented Commands"

### ISSUE THREAD

**Issue by AlanSwenson** [sacherjj/simple_zpl2#177]
@sacherjj 
### Description

Would you be interested in PRs for things on this list?
https://simple-zpl2.readthedocs.io/en/latest/not_implemented.html

**Comment by sacherjj** [comment]
I'll merge in additions for those.  I no longer really use this package.  I wrote it to be used at a former job.

**Comment by gugsrs** [comment]
@sacherjj will you release new versions of the pypy package?

**Comment by sacherjj** [comment]
Just pushed 0.3.0 to PyPi.
