### ISSUE TITLE
Basic Example not work.

### ISSUE THREAD

**Issue by maxiplux** [sacherjj/simple_zpl2#62]
Hello , Thanks for your amazing work .
I have a question about basic example,  what is the signature of arguments to call ZPLDocument() ? 

python /Users/juan/Downloads/impresorafinal/myzplejemplo.py
MacBook-Air-de-Juan:impresorafinal juan$ python /Users/juan/Downloads/impresorafinal/myzplejemplo.py
Traceback (most recent call last):
  File "/Users/juan/Downloads/impresorafinal/myzplejemplo.py", line 4, in <module>
    zpl = ZPLDocument()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/simple_zpl2/zpl_document.py", line 1954, in __init__
    super().__init__()
TypeError: super() takes at least 1 argument (0 given)
MacBook-Air-de-Juan:impresorafinal juan$

TypeError: super() takes at least 1 argument (0 given)

**Comment by sacherjj** [comment]
Try with a modern Python like 3.4+.  The super() arguments in classes are different with legacy Python.

**Comment by maxiplux** [comment]
Thanks for your wonderful work.
Have a nice day.

*Student Master of Science in Computer Science  *
